package com.gojek.GojekGol;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class GameOfLifeTest {
    @Test public void firstStepTest() {
        assertEquals(0,0);
    }
}
