package com.gojek.GameOfLife;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class GameOfLifeTest {
    @Test public void testAppHasAGreeting() {
        GameOfLife classUnderTest = new GameOfLife();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
